blank_issues_enabled: false
contact_links:
  - name: Scratch Coding Hut Forum
    url: https://scratch.mit.edu/discuss/topic/652178/
    about: Post here for stuff relating to the shop itself, example: make an order.
